spring:
  application:
    name: service-a
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 20104
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:20001/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    metadata-map:
#      zone: xuhui
      instanceId: 3
#    initial-status: starting
#    initial-status: out_of_service