spring:
  application:
    name: service-a
server:
  port: 20104
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:20001/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    initial-status: starting
#    initial-status: out_of_service
gray:
  enabled: true
  client:
    instance:
      grayEnroll: true #是否在启动后自动注册成灰度实例
  server:
    url: http://localhost:20202 #灰度服务端的url