spring:
  application:
    name: service-b
server:
  port: 20102
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:20001/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}
feign:
  hystrix:
    enabled: true

gray:
  request:
    track:
      web:
        need:
          uri: enable
          ip: enable
          method: enable
          headers: test,test-mm
          parameters: version,test
        path-patterns: /*
  load:
    enabled: true
    gray-instances:
      - serviceId: service-a
        instance-id: service-a:20104
        policy-definitions:
          - policyId: policy-1
            alias: policy-1
            list:
              - id: decision-1
                name: HttpHeader
                infos:
                  compare-mode: EQUAL
                  header: _graytrack_header__test
                  values: true
#  client:
#    instance:
#      grayEnroll: false #是否在启动后自动注册成灰度实例
#    serverUrl: http://localhost:20202 #灰度服务端的url