spring:
  application:
    name: api-gateway
server:
  port: 20301
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20001/eureka/

ribbon:
  #    ReadTimeout: 30000
  #    ConnectTimeout: 30000
  eureka:
    enabled: true
zuul:
  prefix: /gateway #为zuul设置一个公共的前缀
  ribbonIsolationStrategy: THREAD
#  routes:
#    eureka-client: #随便定义，当不存在serviceId时，默认该值为serviceId（就是注册服务的名称，属性spring.application.name）
#      path: /client/** #匹配/techouse/usersystem/** 均路由到cloud-client
#      serviceId: eureka-client #指定路由到的serviceId
gray:
  request:
    track:
      web:
        need:
          uri: enable
          ip: enable
          method: enable
          headers: test,test-mm
          parameters: version,test
        path-patterns: /*
  load:
    enabled: true
    gray-instances:
      - serviceId: service-a
        instance-id: service-a:20104
        policy-definitions:
          - policyId: policy-1
            alias: policy-1
            list:
              - id: decision-1
                name: HttpHeader
                infos:
                  compare-mode: EQUAL
                  header: _graytrack_header__test
                  values: true
#                  _graytrack_heander__test: true

